id: "values-vision"
orientation: normal
sectioncolor: yellow
hascolorbg: false
image: 'values.png'
imgwidth: '477'
imgheight: '530'
haslargetitle: true
largetitle: 'Values & Vision'
hassmalltitle: false
smalltitle: ''
hasdescription: true
description: "We manifest our values and vision as a community of practice."
hasbutton: true
buttonaction: "Read the"
buttontitle: "Manifesto"
buttonlink: "uploads/whitepaper.pdf"
