---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: ''
  label: Cities
  create: all
  match: Barcelona/*
  new_doc_ext: html
- type: directory
  path: _data
  label: Content of General pages
  create: documents
  match: "**/*"
  new_doc_ext: yml
upload_dir: images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
