---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: "*"
  label: Cities
  create: all
  match: "*(Barcelona|Amsterdam|Paris|Santiago|Shenzhen|Ekurhuleni|Thimphu|Georgia|Sacramento|Detroit|Somerville|Boston|Cambridge|Kerala|Toulouse|Occitanie-Region|Brest|Curitiba|Kamakura|Sorocaba|Mexico-city|Seoul|Zagreb|Velsen|PueblaBelo-Horizonte|Auvergne-rhone-alpes|Oakland|Sao-paulo|Yucatan|Hamburg|Rennes|Plymouth|Recife)"
- type: directory
  path: _data
  label: Data
  create: documents
  match: "**/*"
  new_doc_ext: yml
upload_dir: images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
